baseurl: https://newdudesfootball.netlify.app/
title: "It's Football, Dudes! Fantasy League"
author: "Giuliano Sposito"
canonifyurls: yes
paginate: 5
theme: aether
params:
  brand: It's Football, Dudes! Fantasy League
  description: NFL Fantasy League
  bgimg: /img/wilson_background_w.jpg
googleAnalytics: "UA-148711241-1"
markup:
  highlight:
    style: igor
  goldmark:
    renderer:
      unsafe: true
